language: java

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: zipped_project
    skip_cleanup: true
    bucket: mbdebbeler-apprenticeship-2
    region: us-east-2
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mbdebbeler-apprenticeship-2
    key: latest.zip
    bundle_type: zip
    application: java-http-server
    deployment_group: apprenticeship
    wait_until_deployed: true
    on:
      all_branches: true
    region: us-east-2

script:
  - ./gradlew build && ./gradlew test
  - zip -r latest *
  - mkdir -p zipped_project
  - mv latest.zip zipped_project/latest.zip
