language: java

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: mbdebbeler/java-http-server
    bucket: mbdebbeler-apprenticeship-2
    region: us-east-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mbdebbeler-apprenticeship-2
    key: latest.zip
    bundle_type: zip
    application: java-http-server
    deployment_group: apprenticeship
    region: us-east-2
    on: *2

script:
  - "./gradlew test"
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip