version: 0.0
os: linux
files:
  - source: out/artifacts/java_http_server_jar/java-http-server.jar
    destination: /opt
  - source: deploy_server.sh
    destination: /opt
hooks:
  ApplicationStart:
    - location: deploy_server.sh