version: 0.0
os: linux
files:
  - source: out/artifacts/java_http_server_jar/java-http-server.jar
    destination: /opt
  - source: /scripts/start_server.sh
    destination: /opt
  - source: /Logs
    destination: /opt
hooks:
  ApplicationStart:
    - location: /opt/start_server.sh

