version: 0.0
os: linux
files:
  - source: out/artifacts/just_hello_world_jar/just-hello-world.jar
    destination: /opt
  - source: deploy_server.sh
    destination: /opt
hooks:
  ApplicationStart:
    - location: deploy_server.sh