version: 0.0
os: linux
files:
  - source: gradle/wrapper/gradle-wrapper.jar
    destination: /opt
  - source: /scripts/start_server.sh
    destination: /opt
  - source: /Logs
    destination: /opt
hooks:
  AfterInstall:
    - location: opt/start_server.sh

