version: 0.0
os: linux
files:
  - source: out/artifacts/server-jar/server.jar
    destination: /opt
  - source: deploy_server.sh
    destination: /opt
  - source: Logs
    destination: /opt
hooks:
  ApplicationStart:
    - location: deploy_server.sh

